 var  keywords = [
    "break", 
	"case",
	"catch",
	"continue",
    "default",
    "delete",
    "do", 
    "else",
    "finally", 
    "for", 
    "function",
    "if",
    "in",
    "instanceof",
    "return",
    "switch",
    "throw",
    "try", 
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "String",
    "Array",
    "Object"
];
var available_tags = [
    "html",
    "label",
    "textarea",
    "div",
    "span",
    "form",
    "a",
    "h1",
    "h2",
    "h3", 
    "h4",
    "h5",
    "input",
    "head",
    "section",
    "header",
    "body"
 ];	    
 var searchAndReplace = [];   
 var cssPropertyValueMap =  {
   "all":[
      "initial",
      "unset",
      "inherit"
   ],
   "animation":[
      "[animation-name] [animation-duration] [animation-timing-function] [animation-delay] [animation-iteration-count] [animation-direction] [animation-fill-mode] [animation-play-state]"
   ],
   "animation-delay":[
      "0s",
      "@keyframes"
   ],
   "direction":[
      "ltr",
      "rtl"
   ],
   "animation-direction":[
      "normal",
      "reverse",
      "alternate-reverse",
      "alternate",
      "@keyframes"
   ],
   "animation-duration":[
      "0s",
      "@keyframes"
   ],
   "animation-fill-mode":[
      "none",
      "forwards",
      "both",
      "backwards"
   ],
   "animation-iteration-count":[
      "1",
      "infinite",
      "@keyframes"
   ],
   "animation-name":[
      "none",
      "[ custom identifier ]",
      "@keyframes",
      "@keyframes"
   ],
   "animation-timing-function":[
      "ease",
      "step-start",
      "step-end",
      "linear",
      "ease-out",
      "ease-in-out",
      "ease-in",
      "@keyframes"
   ],
   "animation-play-state":[
      "running",
      "paused",
      "@keyframes"
   ],
   "visibility":[
      "visible",
      "hidden",
      "collapse"
   ],
   "backface-visibility":[
      "visible",
      "hidden"
   ],
   "background":[
      "[background-color] [background-image] [background-repeat] [background-attachment] [background-position] / [ background-size] [background-origin] [background-clip]",
      "background-size",
      "background-position",
      "background-origin",
      "background-clip",
      "background-origin",
      "background-origin",
      "background-clip"
   ],
   "background-attachment":[
      "scroll",
      "local",
      "fixed",
      "background-attachment"
   ],
   "background-blend-mode":[
      "normal",
      "soft-light",
      "screen",
      "saturation",
      "overlay",
      "multiply",
      "luminosity",
      "lighten",
      "hue",
      "hard-light",
      "exclusion",
      "difference",
      "darken",
      "color-dodge",
      "color-burn",
      "color"
   ],
   "color":[
      "lightgoldenrodyellow",
      "mediumspringgreen",
      "mediumaquamarine",
      "mediumvioletred",
      "mediumturquoise",
      "mediumslateblue",
      "lightslategrey",
      "blanchedalmond",
      "lightsteelblue",
      "lightslategray",
      "cornflowerblue",
      "darkolivegreen",
      "mediumseagreen",
      "lightseagreen",
      "palevioletred",
      "darkslategrey",
      "darkslateblue",
      "paleturquoise",
      "lavenderblush",
      "palegoldenrod",
      "darkslategray",
      "darkgoldenrod",
      "darkturquoise",
      "rebeccapurple",
      "midnightblue",
      "lemonchiffon",
      "darkseagreen",
      "mediumorchid",
      "mediumpurple",
      "antiquewhite",
      "lightskyblue",
      "lightsalmon",
      "darkmagenta",
      "lightyellow",
      "deepskyblue",
      "forestgreen",
      "saddlebrown",
      "yellowgreen",
      "springgreen",
      "navajowhite",
      "greenyellow",
      "floralwhite",
      "lightgreen",
      "mediumblue",
      "indianred",
      "blueviolet",
      "ghostwhite",
      "darksalmon",
      "darkorchid",
      "papayawhip",
      "powderblue",
      "sandybrown",
      "lightcoral",
      "darkorange",
      "dodgerblue",
      "aquamarine",
      "whitesmoke",
      "darkviolet",
      "chartreuse",
      "goldenrod",
      "palegreen",
      "slategray",
      "gainsboro",
      "chocolate",
      "firebrick",
      "slategrey",
      "burlywood",
      "royalblue",
      "mistyrose",
      "rosybrown",
      "orangered",
      "lawngreen",
      "mintcream",
      "aliceblue",
      "steelblue",
      "olivedrab",
      "lightcyan",
      "lightpink",
      "cadetblue",
      "turquoise",
      "darkkhaki",
      "limegreen",
      "darkgreen",
      "peachpuff",
      "lightblue",
      "lightgrey",
      "slateblue",
      "lightgray",
      "cornsilk",
      "darkblue",
      "seagreen",
      "indigo",
      "darkcyan",
      "darkgrey",
      "darkgray",
      "moccasin",
      "honeydew",
      "deeppink",
      "lavender",
      "seashell",
      "dimgray",
      "magenta",
      "crimson",
      "oldlace",
      "hotpink",
      "darkred",
      "fuchsia",
      "thistle",
      "dimgrey",
      "skyblue",
      "orchid",
      "maroon",
      "yellow",
      "purple",
      "silver",
      "salmon",
      "orange",
      "violet",
      "bisque",
      "sienna",
      "tomato",
      "brown",
      "coral",
      "beige",
      "white",
      "ivory",
      "black",
      "azure",
      "wheat",
      "green",
      "olive",
      "linen",
      "khaki",
      "cyan",
      "snow",
      "lime",
      "peru",
      "pink",
      "plum",
      "blue",
      "navy",
      "teal",
      "gray",
      "gold",
      "aqua",
      "grey",
      "tan",
      "red"
   ],
   "background-color":[
      "transparent"
   ],
   "clip":[
      "auto",
      "clip-path"
   ],
   "clip-path":[
      "none",
      "view-box",
      "stroke-box",
      "fill-box",
      "clip"
   ],
   "background-clip":[
      "border-box",
      "padding-box",
      "content-box",
      "background-clip"
   ],
   "background-image":[
      "none",
      "url(\"path/file.png\")"
   ],
   "background-origin":[
      "padding-box",
      "content-box",
      "border-box",
      "background-attachment"
   ],
   "position":[
      "static",
      "sticky",
      "relative",
      "page",
      "fixed",
      "center",
      "absolute"
   ],
   "background-position":[
      "0% 0%",
      "right bottom",
      "left top",
      "center center",
      "background-position"
   ],
   "background-repeat":[
      "repeat",
      "space",
      "round",
      "repeat-y",
      "repeat-x",
      "repeat no-repeat",
      "no-repeat",
      "background-repeat"
   ],
   "background-size":[
      "auto",
      "cover",
      "contain"
   ],
   "order":[
      "0"
   ],
   "border":[
      "[border-width] [border-style] [border-color]",
      "border-image"
   ],
   "border-collapse":[
      "separate",
      "collapse"
   ],
   "border-color":[
      "transparent"
   ],
   "top":[
      "auto"
   ],
   "border-top":[
      "[border-width] [border-style] [border-color]"
   ],
   "border-top-color":[
      "transparent"
   ],
   "right":[
      "auto"
   ],
   "border-right":[
      "[border-width] [border-style] [border-color]"
   ],
   "border-right-color":[
      "transparent"
   ],
   "bottom":[
      "auto"
   ],
   "border-bottom":[
      "[border-width] [border-style] [border-color]"
   ],
   "border-bottom-color":[
      "transparent"
   ],
   "left":[
      "auto"
   ],
   "border-left":[
      "[border-width] [border-style] [border-color]"
   ],
   "border-left-color":[
      "transparent"
   ],
   "border-radius":[
      "0"
   ],
   "border-top-left-radius":[
      "0"
   ],
   "border-top-right-radius":[
      "0"
   ],
   "border-bottom-left-radius":[
      "0"
   ],
   "border-bottom-right-radius":[
      "0"
   ],
   "border-image":[
      "[border-image-source] [border-image-slice] / [border-image-width] [border-image-width] / [border-image-outset] [border-image-repeat]"
   ],
   "border-image-source":[
      "none",
      "url(\"path/file.png\")"
   ],
   "border-image-slice":[
      "100%"
   ],
   "width":[
      "auto"
   ],
   "border-image-width":[
      "1"
   ],
   "border-image-outset":[
      "0"
   ],
   "border-image-repeat":[
      "stretch",
      "space",
      "round",
      "repeat"
   ],
   "border-spacing":[
      "0"
   ],
   "border-style":[
      "none",
      "solid",
      "ridge",
      "outset",
      "inset",
      "hidden",
      "groove",
      "double",
      "dotted",
      "dashed"
   ],
   "border-top-style":[
      "none",
      "solid",
      "ridge",
      "outset",
      "inset",
      "hidden",
      "groove",
      "double",
      "dotted",
      "dashed"
   ],
   "border-right-style":[
      "none",
      "solid",
      "ridge",
      "outset",
      "inset",
      "hidden",
      "groove",
      "double",
      "dotted",
      "dashed"
   ],
   "border-bottom-style":[
      "none",
      "solid",
      "ridge",
      "outset",
      "inset",
      "hidden",
      "groove",
      "double",
      "dotted",
      "dashed"
   ],
   "border-left-style":[
      "none",
      "solid",
      "ridge",
      "outset",
      "inset",
      "hidden",
      "groove",
      "double",
      "dotted",
      "dashed"
   ],
   "border-width":[
      "medium",
      "thin",
      "thick"
   ],
   "border-top-width":[
      "medium",
      "thin",
      "thick"
   ],
   "border-right-width":[
      "medium",
      "thin",
      "thick"
   ],
   "border-bottom-width":[
      "medium",
      "thin",
      "thick"
   ],
   "border-left-width":[
      "medium",
      "thin",
      "thick"
   ],
   "box-decoration-break":[
      "slice",
      "clone"
   ],
   "box-shadow":[
      "none"
   ],
   "box-sizing":[
      "content-box",
      "padding-box",
      "border-box",
      "padding-box"
   ],
   "break-before":[
      "auto",
      "right",
      "page",
      "left",
      "column",
      "avoid-page",
      "avoid-column",
      "avoid",
      "always"
   ],
   "break-after":[
      "auto",
      "right",
      "page",
      "left",
      "column",
      "avoid-page",
      "avoid-column",
      "avoid",
      "always"
   ],
   "break-inside":[
      "auto",
      "avoid-page",
      "avoid-column",
      "avoid"
   ],
   "caption-side":[
      "top",
      "bottom"
   ],
   "clear":[
      "none",
      "right",
      "left",
      "both"
   ],
   "clear-after":[
      "none",
      "top",
      "start",
      "right",
      "outside",
      "left",
      "inside",
      "end",
      "descendants",
      "bottom",
      "both"
   ],
   "column-fill":[
      "balance",
      "auto"
   ],
   "column-span":[
      "none",
      "all"
   ],
   "column-width":[
      "auto"
   ],
   "column-count":[
      "auto"
   ],
   "column-gap":[
      "normal"
   ],
   "column-rule":[
      "[column-rule-width] [column-rule-style] [column-rule-color]"
   ],
   "column-rule-color":[
      "[ Initial value depends on the user agent ]"
   ],
   "column-rule-style":[
      "none",
      "solid",
      "ridge",
      "outset",
      "inset",
      "hidden",
      "groove",
      "double",
      "dotted",
      "dashed"
   ],
   "column-rule-width":[
      "medium",
      "thin",
      "thick"
   ],
   "columns":[
      "[column-width] [column-count]"
   ],
   "content":[
      "normal",
      "open-quote",
      "none",
      "no-open-quote",
      "no-close-quote",
      "icon",
      "close-quote",
      ":before",
      ":after"
   ],
   "counter-increment":[
      "none"
   ],
   "counter-reset":[
      "none"
   ],
   "cursor":[
      "auto",
      "zoom-out",
      "zoom-in",
      "wait",
      "w-resize",
      "vertical-text",
      "url(\"path/file.png\")",
      "text",
      "sw-resize",
      "se-resize",
      "s-resize",
      "row-resize",
      "progress",
      "pointer",
      "nwse-resize",
      "nw-resize",
      "ns-resize",
      "not-allowed",
      "none",
      "no-drop",
      "nesw-resize",
      "ne-resize",
      "n-resize",
      "move",
      "help",
      "ew-resize",
      "e-resize",
      "default",
      "crosshair",
      "copy",
      "context-menu",
      "col-resize",
      "cell",
      "all-scroll",
      "alias"
   ],
   "display":[
      "inline",
      "table-row-group",
      "table-row",
      "table-header-group",
      "table-footer-group",
      "table-column-group",
      "table-column",
      "table-cell",
      "table-caption",
      "table",
      "run-in",
      "run-in",
      "none",
      "list-item",
      "inline-table",
      "inline-flex",
      "inline-block",
      "flex",
      "container",
      "compact",
      "block"
   ],
   "empty-cells":[
      "show",
      "hide"
   ],
   "float":[
      "none",
      "right",
      "left"
   ],
   "flex":[
      "[flex-grow] [flex-shrink] [flex-basis]",
      "none"
   ],
   "flex-basis":[
      "auto"
   ],
   "flex-direction":[
      "row",
      "row-reverse",
      "column-reverse",
      "column"
   ],
   "flex-flow":[
      "[flex-direction] [flex-wrap]"
   ],
   "flex-grow":[
      "0"
   ],
   "flex-shrink":[
      "1"
   ],
   "flex-wrap":[
      "nowrap",
      "wrap-reverse",
      "wrap"
   ],
   "align-items":[
      "stretch",
      "flex-start",
      "flex-end",
      "center",
      "baseline"
   ],
   "align-self":[
      "auto",
      "stretch",
      "flex-start",
      "flex-end",
      "center",
      "baseline"
   ],
   "align-content":[
      "stretch",
      "space-between",
      "space-around",
      "flex-start",
      "flex-end",
      "center"
   ],
   "justify-content":[
      "flex-start",
      "space-between",
      "space-around",
      "flex-end",
      "center"
   ],
   "filter":[
      "none"
   ],
   "font":[
      "[font-style] [font-variant] [font-weight] [font-stretch] [font-size] / [line-height] [font-family]"
   ],
   "font-family":[
      "'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;",
      "'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"
   ],
   "font-feature-settings":[
      "normal"
   ],
   "font-size":[
      "medium",
      "xx-small",
      "xx-large",
      "x-small",
      "x-large",
      "smaller",
      "small",
      "larger",
      "large"
   ],
   "font-stretch":[
      "normal",
      "ultra-expanded",
      "ultra-condensed",
      "semi-expanded",
      "semi-condensed",
      "extra-expanded",
      "extra-condensed",
      "expanded",
      "condensed"
   ],
   "font-size-adjust":[
      "none"
   ],
   "font-synthesis":[
      "weight style",
      "weight",
      "style",
      "none"
   ],
   "font-kerning":[
      "auto",
      "normal",
      "none"
   ],
   "font-variant":[
      "normal",
      "unicase",
      "titling-caps",
      "small-caps",
      "petite-caps",
      "all-small-caps",
      "all-petite-caps"
   ],
   "font-variant-caps":[
      "normal",
      "unicase",
      "titling-caps",
      "small-caps",
      "petite-caps",
      "all-small-caps",
      "all-petite-caps"
   ],
   "font-style":[
      "normal",
      "oblique",
      "italic"
   ],
   "font-weight":[
      "normal",
      "lighter",
      "bolder",
      "bold",
      "900",
      "800",
      "700",
      "600",
      "500",
      "400",
      "300",
      "200",
      "100"
   ],
   "hanging-punctuation":[
      "none",
      "last force-end",
      "last allow-end",
      "last",
      "force-end",
      "first force-end",
      "first allow-end",
      "first",
      "allow-end"
   ],
   "height":[
      "auto"
   ],
   "hyphens":[
      "manual",
      "none",
      "auto"
   ],
   "image-rendering":[
      "auto",
      "pixelated",
      "crisp-edges"
   ],
   "image-resolution":[
      "1dppx",
      "snap",
      "from-image"
   ],
   "image-orientation":[
      "0deg",
      "from-image"
   ],
   "isolation":[
      "auto",
      "isolate"
   ],
   "letter-spacing":[
      "normal"
   ],
   "line-break":[
      "auto",
      "strict",
      "normal",
      "loose"
   ],
   "line-height":[
      "normal"
   ],
   "list-style":[
      "[list-style-type] [list-style-position] [list-style-image]"
   ],
   "list-style-image":[
      "none"
   ],
   "list-style-position":[
      "outside",
      "inside"
   ],
   "list-style-type":[
      "disc",
      "upper-roman",
      "upper-latin",
      "upper-alpha",
      "square",
      "none",
      "lower-roman",
      "lower-latin",
      "lower-greek",
      "lower-alpha",
      "georgian",
      "decimal-leading-zero",
      "decimal",
      "circle",
      "armenian"
   ],
   "margin":[
      "[margin-top] [margin-right] [margin-bottom] [margin-left]"
   ],
   "margin-left":[
      "0",
      "auto"
   ],
   "margin-right":[
      "0",
      "auto"
   ],
   "margin-top":[
      "0",
      "auto"
   ],
   "margin-bottom":[
      "0",
      "auto"
   ],
   "mask-type":[
      "luminance",
      "alpha"
   ],
   "max-height":[
      "none"
   ],
   "max-width":[
      "none"
   ],
   "min-height":[
      "0",
      "auto"
   ],
   "min-width":[
      "0",
      "auto"
   ],
   "mix-blend-mode":[
      "normal",
      "soft-light",
      "screen",
      "saturation",
      "overlay",
      "multiply",
      "luminosity",
      "lighten",
      "hue",
      "hard-light",
      "exclusion",
      "difference",
      "darken",
      "color-dodge",
      "color-burn",
      "color"
   ],
   "object-fit":[
      "fill",
      "scale-down",
      "none",
      "cover",
      "contain"
   ],
   "object-position":[
      "50% 50%",
      "right bottom",
      "left top",
      "center center"
   ],
   "opacity":[
      "1"
   ],
   "orphans":[
      "2"
   ],
   "outline":[
      "[outline-color] [outline-style] [outline-width]"
   ],
   "outline-color":[
      "invert",
      "invert"
   ],
   "outline-offset":[
      "0"
   ],
   "outline-style":[
      "none",
      "solid",
      "ridge",
      "outset",
      "inset",
      "groove",
      "double",
      "dotted",
      "dashed",
      "auto"
   ],
   "outline-width":[
      "medium",
      "thin",
      "thick"
   ],
   "overflow":[
      "visible",
      "scroll",
      "hidden",
      "auto"
   ],
   "overflow-x":[
      "visible",
      "scroll",
      "hidden",
      "auto"
   ],
   "overflow-y":[
      "visible",
      "scroll",
      "hidden",
      "auto"
   ],
   "overflow-wrap":[
      "normal",
      "break-word",
      "word-wrap"
   ],
   "padding":[
      "[padding-top] [padding-right] [padding-bottom] [padding-left]"
   ],
   "padding-top":[
      "0"
   ],
   "padding-bottom":[
      "0"
   ],
   "padding-left":[
      "0"
   ],
   "padding-right":[
      "0"
   ],
   "page-break-after":[
      "auto",
      "right",
      "left",
      "avoid",
      "always"
   ],
   "page-break-before":[
      "auto",
      "right",
      "left",
      "avoid",
      "always"
   ],
   "page-break-inside":[
      "auto",
      "avoid"
   ],
   "perspective":[
      "none"
   ],
   "perspective-origin":[
      "50% 50%",
      "top",
      "right",
      "left",
      "center",
      "bottom"
   ],
   "pointer-events":[
      "auto",
      "none"
   ],
   "quotes":[
      "[ Initial value depends on the user agent ]",
      "none",
      ":before",
      ":after"
   ],
   "resize":[
      "none",
      "vertical",
      "horizontal",
      "both"
   ],
   "scroll-behavior":[
      "auto",
      "smooth"
   ],
   "scroll-snap-coordinate":[
      "none",
      "right bottom",
      "margin-box",
      "left center",
      "border-box",
      "border-box",
      "margin-box"
   ],
   "scroll-snap-destination":[
      "0px 0px",
      "top bottom",
      "left right",
      "center center"
   ],
   "scroll-snap-type":[
      "none",
      "proximity",
      "mandatory"
   ],
   "tab-size":[
      "8"
   ],
   "table-layout":[
      "auto",
      "fixed"
   ],
   "text-align":[
      "[ Initial value depends on the writing direction (ltr or rtl) ]",
      "start end",
      "start",
      "right",
      "match-parent",
      "left",
      "justify",
      "end",
      "center"
   ],
   "text-align-last":[
      "auto",
      "start",
      "right",
      "left",
      "justify",
      "end",
      "center"
   ],
   "text-combine-upright":[
      "none",
      "all",
      "-webkit-text-combine"
   ],
   "text-decoration":[
      "[text-decoration-line] [text-decoration-style] [text-decoration-color]"
   ],
   "text-decoration-color":[

   ],
   "text-decoration-line":[
      "none",
      "underline",
      "overline",
      "line-through",
      "blink"
   ],
   "text-decoration-skip":[
      "none",
      "spaces",
      "objects",
      "ink",
      "edges",
      "box-decoration"
   ],
   "text-decoration-style":[
      "solid",
      "wavy",
      "double",
      "dotted",
      "dashed"
   ],
   "text-emphasis":[
      "[text-emphasis-style] [text-emphasis-color]",
      "text-emphasis-position"
   ],
   "text-emphasis-style":[
      "none",
      "triangle",
      "sesame",
      "open",
      "filled",
      "double-circle",
      "dot",
      "circle"
   ],
   "text-emphasis-color":[

   ],
   "text-emphasis-position":[
      "over right",
      "over left",
      "below right",
      "below left"
   ],
   "text-indent":[
      "0"
   ],
   "text-justify":[
      "auto",
      "none",
      "inter-word",
      "distribute"
   ],
   "text-orientation":[
      "mixed",
      "use-glyph-orientation",
      "upright",
      "sideways-right",
      "sideways-left",
      "sideways"
   ],
   "text-overflow":[
      "clip",
      "ellipsis"
   ],
   "text-rendering":[
      "auto",
      "optimizeSpeed",
      "optimizeLegibility",
      "geometricPrecision"
   ],
   "text-shadow":[
      "none"
   ],
   "text-underline-position":[
      "auto",
      "under right",
      "under left",
      "under",
      "right",
      "left"
   ],
   "touch-action":[
      "auto",
      "pan-y",
      "pan-y",
      "pan-x",
      "pan-up",
      "pan-right",
      "pan-left",
      "pan-down",
      "none",
      "manipulation"
   ],
   "transform":[
      "none"
   ],
   "transform-box":[
      "border-box",
      "view-box",
      "fill-box"
   ],
   "transform-origin":[
      "50% 50%",
      "top",
      "right",
      "left",
      "center",
      "bottom"
   ],
   "transform-style":[
      "flat",
      "preserve-3d"
   ],
   "text-transform":[
      "none",
      "uppercase",
      "lowercase",
      "full-width",
      "capitalize",
      "full-width"
   ],
   "transition":[
      "[transition-property] [transition-duration] [transition-timing-function] [transition-delay]"
   ],
   "transition-property":[
      "all",
      "none",
      "[ A comma-separated list of property names ]"
   ]
}


// Od internet gi zemavme site  na mnogu mudar nacin
function web_scraping() {
    $("section").each(function(){
        var property = $(this).find(".property").html().trim();
        var values   = [];
		
        $(this).find("code").each(function() {
            var value = $(this).html().trim();
            if(!/<a href/g.test(value))
                values.push(value);
		})
       cssPropertyValueMap[property] = values; 
    });
} 

var string_regex = /(".*?")/g;
var string_hightlight = "<span class='string'>$1</span>"; 

var string_regex1 = /('.*?')/g;
var string_hightlight1 = "<span class=string>$1</span>"; 

var function_regex = /(function\s+)(.+?\b)/g;
var function_highlight = "$1<span class='fn-name'>$2</span>";

var instance_regex	 = /(\w+?)(\.)(.+?\b)/g;
var instance_highlight = "<span class='inst'>$1</span>$2<span class='method'>$3</span>";

var this_regex = /(\b)(this)(\b)/g;
var this_highlight = "$1<span class='this'>$2</span>$3";
  
var new_regex = /(\b)(new)(\b)/g;
var new_highlight	= "$1<span class='new'>$2</span>$3";
  
var number_regex = /\b([0-9]+\.{0,1}[0-9]*)/g;
var number_highlight = "<span class='number'>$1</span>";
    
var comment_regex = /(\/\/.*)/g;
var comment_highlight = "<span class='commentar' style='color:gray !important;'>$1</span>";
  
var brackets_open_regex = /(\{)/g;
var bracket_open_highlight = "<span class='brackets'>$1</span>";

var brackets_close_regex = /(\})/g;
var bracket_close_highlight = "<span class='brackets-closed'>$1</span>";

var tag_regex = /(&lt\/{0,1})([a-zA-Z0-9]*)(\b)/g;
var tag_highlight = "$1<span class='tag'>$2</span>$3"; 